### ISSUE TITLE
Incorrect Smithing Construct Icon

### ISSUE THREAD

**Issue by Doge229** [zeldamods/objmap-totk#100]
The Smithing Construct in the Spirit Temple has the wrong icon on the map.

Current icon on the Object Map:
![image](https://github.com/zeldamods/objmap-totk/assets/30128806/4c023cd1-3e45-4778-bcb6-a5c2c74985db)
 
In-game icon on the map:
![image](https://github.com/zeldamods/objmap-totk/assets/30128806/e1fc54ea-fdd5-49a6-a25f-7fbd8335d41b)

**Comment by savage13** [comment]
Updated with new icon for this Smithing construct
<img width="755" alt="Screen Shot 2023-12-02 at 11 04 44 AM" src="https://github.com/zeldamods/objmap-totk/assets/126514/f00eb5cd-9832-4928-894e-4258078f95ec">

**Comment by savage13** [comment]
Close fd40021
