### ISSUE TITLE
Korok PS-18 Wrong Z position

### ISSUE THREAD

**Issue by Helios2357** [zeldamods/objmap-totk#109]
it shows z=4.87 (incorrect) and not z~-100 (actual z level)
(sorry if issue is stupid/"seriously? opening an issue for ONE korok?", idk where to put this otherwise.)

**Comment by savage13** [comment]
Thanks for the bug fix. :)

The coordinates in the database are off by ~106; this is known.

You can change the coordinates so they match the in-game coordinates by doing
Setting > Use In-Game Coordinates > Display Coordinates as those In-Game
This should fix the vertical values by 106.

**Comment by Helios2357** [comment]
ohhhhh tyy!!
