### ISSUE TITLE
Climbing Outfit ID 16848133674008415024 incorrect location

### ISSUE THREAD

**Issue by quaintnate** [zeldamods/objmap-totk#110]
This armor piece is displayed incorrectly, it is actually in the Zora region.

Climbing Outfit
 Cave__Cave_HyruleRidge_0000_GroupSet_000
 ID [16848133674008415024](https://objmap-totk.zeldamods.org/#/map/z6,-1188,-642.5,Surface?id=MainField,Cave__Cave_HyruleRidge_0000_GroupSet_000%20,0xe9d0984faf918b30)

**Comment by savage13** [comment]
The link you gave is for a Location, not an piece of Armor. 

Links to each piece is below.
- [Climbing Gear](https://objmap-totk.zeldamods.org/#/map/z6,-1214.24,-773.97,Surface?id=MainField,Cave__Cave_HyruleRidge_0000_GroupSet_000%20,0x85026de3b7751cff)
- [Climbing Boots](https://objmap-totk.zeldamods.org/#/map/z6,2849.71,-542.59,Surface?id=MainField,Cave__Cave_Lanayru_0033_GroupSet_000%20,0xa891b810c76f41bf)
- [Climber's Bandanna](https://objmap-totk.zeldamods.org/#/map/z6,3436,-495.5,Surface?id=MainField,Cave__Cave_Lanayru_0057_GroupSet_000%20,0xc6efdd186a1563a4)
