### ISSUE TITLE
Fix typos with item bundles

### ISSUE THREAD

**Issue by Catobat** [zeldamods/objmap-totk#111]
Not sure if this comes from radar-totk, but here are some typos that can be found in missing.csv:
Item_Ore_D_Bundle_A, Topax x3
Item_Ore_L_Bundle_A, Zonalite x3
Item_Ore_L_Bundle_B, Zonalite x5

**Comment by Catobat** [comment]
Additionally, Bomb Flower bundles (BombFruit_Bundle_A, BombFruit_Bundle_B and BombFruit_Bundle_D) have no nice names.

**Comment by savage13** [comment]
Fixed.
