### ISSUE TITLE
Hide objects on different layers?

### ISSUE THREAD

**Issue by Paperzlel** [zeldamods/objmap-totk#15]
Just a thing so folks can confirm if a korok is in the sky or on the surface, same for shrines, and eventually dungeons if/when they are implemented.
Also, for the lines, when going between layers perhaps a lighten/darken effect would be a good idea? Just a side thought. Great job as well for getting this up so quickly!

**Comment by savage13** [comment]
I have implemented this for Koroks, Shrines, Lightroots, Towers, and Location names.  

I am not sure what you are referring to by 

> Also, for the lines, when going between layers perhaps a lighten/darken effect would be a good idea? 

I just realized that the polylines, markers and such do not respect the layers.

**Comment by Paperzlel** [comment]
Sorry for a late answer but this was so that when mapping out a polyline (mainly for hundo) we could change layers with a more seamless transition between the sky and the surface, per say, with the line colour fading down where it leaves the current layer and moves to the next one, but in hindsight that wouldn't work very well and it would look horrible lol, so maybe alternatively search for if a polyline is on the depths, surface or sky, and then load/unload the lines accordingly? Just because having the lines on the map from the above layer creates clutter and will probably make it hard to see where to go next.

**Comment by savage13** [comment]
I would like to be able to do editing per-layer eventually; I think this may be possible. If I forget about this, please reopen another issue.

Creating a new Caves issues #35
