### ISSUE TITLE
Typos / Chasm misclassification

### ISSUE THREAD

**Issue by LtPeriwinkle** [zeldamods/objmap-totk#21]
When 'show map tower areas' is enabled, Upland Zorana's label reads Upload Zorana. Similarly, Thyphlo Ruins' label says Typhlo Ruins.

Two chasms (Hyrule Ridge and East Gerudo) are incorrectly marked as caves.

**Comment by savage13** [comment]
Typos fixed.  Please wait while I Upload Zorana.

**Comment by savage13** [comment]
Fixed by ac80832
