### ISSUE TITLE
Zonai Reliefs location tags appear on the ground and not on the island

### ISSUE THREAD

**Issue by Paperzlel** [zeldamods/objmap-totk#23]
This is specific to ZonauRelief_04, ZonauRelief_05 and ZonauRelief_07, where the location markers are shown on the surface rather than in the sky. This is probably due to the code seeing its y-level and deciding it is on the ground rather than in the sky.

**Comment by savage13** [comment]
Markers should be in the sky, changed to Ancient Tablet
fixed by 175c53a9bf1a7d348ab096791f67f57b74c712ab

**Comment by leoetlino** [comment]
IMO we should fix this on the client side instead of overwriting the message ID and making the IDs not-unique anymore. (There's also a typo in "Anicent Tablet")

**Comment by savage13** [comment]
Reverted the change and moved the Translation of ZonauRelief_xx from `static.json` to  `LocationMarker.json`
