### ISSUE TITLE
Adding lines between "buddy" koroks?

### ISSUE THREAD

**Issue by Paperzlel** [zeldamods/objmap-totk#24]
This is more of a suggestion (sorry for making so many lol) but could these lines maybe show up on the map? Perhaps search for the relevant KorokCarryProgressKeeper and then the ID of its friend in the placement code? This probably wouldn't look good on a zoom-out so maybe keeping the lines when the map is zoomed in?

**Comment by savage13** [comment]
This was on the list of things to do. :) 
Keep making suggestions.

**Comment by Paperzlel** [comment]
Okay one more to this thread (thanks to Abahob in the discord) but maybe also adding the lines for race koroks? Might be good as well.

**Comment by savage13** [comment]
As in the botw objmap map, if the data exists and we can link them easily it will probably get done. I think I have the buddy koroks, starting block / goal race koroks, along with the flower chase koroks too.  There are newer koroks that I need to delve into.

For example:
https://objmap.zeldamods.org/#/map/z7,-4260.75,-3562.25?id=MainField,A-1,4022716825

**Comment by savage13** [comment]
fixed by 1b3e697
