### ISSUE TITLE
Dashes when searching by map unit

### ISSUE THREAD

**Issue by Chubby-Bub** [zeldamods/objmap-totk#25]
This is an extremely small issue, but searching by map unit won't work unless an en dash is used. For example I must type `map:B–8` and not `map:B-8`. It would be nice if hyphens were also supported, because at first I didn't realize the distinction was necessary and thought it wasn't working. (Note: this applies to the BotW map too.)

**Comment by leoetlino** [comment]
You need to quote the map name because it contains a -.
