### ISSUE TITLE
Line draw tool places when drag clicking in Firefox

### ISSUE THREAD

**Issue by Paperzlel** [zeldamods/objmap-totk#26]
This is a firefox exclusive feature tm, but it's annoying me a great deal. Basically, whenever I try to draw a line, the placement is fine, but when I drag to pan the map, it places a point where my cursor was. This is just on firefox though, not sure if it's specfic to other browsers as well

**Comment by Paperzlel** [comment]
The zooming in/out is also quite janky on Firefox, just as a heads-up. It seems to zoom in/out to every other scale rather than the more smooth scale on Chrome-based browsers. These are both mainly convenience and idk how many folks user firefox but they'd be nice to have,

**Comment by savage13** [comment]
I have experienced this with the line drawing issue as well.  Sadly, the line drawing behavior is contained within a leaflet plugin and is more complicated to fix.  

I am inclined to leave this as is, for now.

**Comment by savage13** [comment]
Fixed by 154c67d847887265cdb7480e06a007a6b18797f9
