### ISSUE TITLE
Add Logic entities

### ISSUE THREAD

**Issue by leoetlino** [zeldamods/objmap-totk#27]

**Comment by savage13** [comment]
Is this the links between objects or the actual Logic data? 
I have a draft implementation of the object linkage.

**Comment by leoetlino** [comment]
The former. I was thinking of having the objmap:
- for each object, show a list of Logic entities that are referencing it
- for each Logic, showing its details + the list of objects that it references

Showing the actual Logic script is far more complicated

**Comment by leoetlino** [comment]
fixed in 1aeffb048a130662c1dcc66950bc2f6cd2500768
