### ISSUE TITLE
Add preset for the ghost soldiers + a list of the weapons they can have

### ISSUE THREAD

**Issue by leoetlino** [zeldamods/objmap-totk#30]
This will require having the FieldMapArea map + the ecosystem data for the depths.

**Comment by savage13** [comment]
If we have the FMA, Weather and Climate data (Lv2 Ignited) is also available.

**Comment by leoetlino** [comment]
Yeah that'd be great. I'll look into it

**Comment by savage13** [comment]
Preset search term for "Shadowy Figures with Weapons" as `Npc_MinusFieldGhost_000`
