### ISSUE TITLE
"Help us with BOTW's Decompilation project" appears despite this being TOTK

### ISSUE THREAD

**Issue by Paperzlel** [zeldamods/objmap-totk#32]
Just an annoying thing every time I have to reset the cookiesfor the map to show updates (or they take a while to be pushed to the site, probably me being impatient) the message shows up every time and it just bugs me it's not TOTK's decomp or just not there.

**Comment by leoetlino** [comment]
TotK basically reuses much of BotW's engine, so the message is valid.

And yes, updates are pushed manually at the moment so spamming refresh or clearing cookies won't do anything. (Also you don't have to clear your cookies, just refresh normally)
