### ISSUE TITLE
Hide lines on different layers?

### ISSUE THREAD

**Issue by Paperzlel** [zeldamods/objmap-totk#39]
This is probably a very tricky thing to do, but perhaps hiding lines made on different layers so that routes become less confusing to look at? If that's hard maybe try a system that allocates X line to the sky, surface or depths, and then that line is hidden when that area is not selected. This mostly goes for when routing around lightroots/shrines, since both lines are shown and it often looks like going from shrine to shrine when that often isn't the case.

**Comment by savage13** [comment]
Fixed by e13f5b82341f00ffae2c18f5fe78cf838165ad79
