### ISSUE TITLE
Reorganise map_type and map_names

### ISSUE THREAD

**Issue by leoetlino** [zeldamods/objmap-totk#42]
For accuracy and consistency with how the game handles bancs, we should:

* remove the merged "Totk" map type and use the actual map type (e.g. MainField or MinusField)
  * we'll need to modify the object map to search for objects on MainField or MinusField if the user is on the overworld map
  * there are various map_name checks that make assumptions about the format of the map_name; those will need to be fixed
* import MainField/Sky bancs as map_type=MainField, map_name=Sky__{bancName} (or map_type=MainField__Sky, map_name={bancName})

This will allow us to make Show All Objects work in a more intuitive way for sky islands:

* have Radar compute the convex hull of every Sky banc
* add a Radar endpoint to turn a position into the name of its Sky banc (by checking which convex hull the point falls into - hopefully we don't have overlaps?)
* when doing "Show All Objects" on the Sky layer, the objmap asks Radar for the name of the Sky banc, and then proceeds to add a search group as usual

A variant of this idea should also work for caves, though we might need to add a "Show nearby cave objects" option.

**Comment by savage13** [comment]
Overlapping regions:
Eldin:
- Eldin_SkyIsland08_OutputAsSky
- Set_SkyIsland_Eldin_G-3_Sky
   - There are 13 points in Eldin_SkyIsland08_OutputAsSky
   - Possible solutions Return multiple regions or merge the groups

Firone:
- Map_SKy_Firone_SmallZonauRuins_Island_B_00 
- Map_SKy_Firone_SmallZonauRuins_Island_D_00
    - These are truly overlapping.  Probably either return the one with the most in the overlapping region (D_00) or just return them both

Gerudo and a Sky Island Monument
- Set_SkyIsland_gerudo_A-6_Sky 
- SkyIsland_Monument_10
    - This one can be prioritized as the Sky Monuments (returned first) as the SkyIsland is contained with the Gerudo region


<img width="1132" alt="Screen Shot 2023-06-06 at 6 04 51 AM" src="https://github.com/zeldamods/objmap-totk/assets/126514/d1b46baa-0dba-4717-bd85-54468aca4ba1">

**Comment by savage13** [comment]
There is one file with one point that did not get a region set of it.
`Set_SkyIsland_Akkare_J-3` with a `OutputPlacemarkLoadPriority`

**Comment by leoetlino** [comment]
Fixed by #67 and zeldamods/radar-totk#8
