### ISSUE TITLE
Estimate location on rails for objects?

### ISSUE THREAD

**Issue by Paperzlel** [zeldamods/objmap-totk#43]
This is purely hypothetical, but what if there was a way to find the location of an object (i.e. a dragon) on its respective rail at X time in the cycle? This probably isn't all that possible due to shrines delaying objects, but if a position could be determined from the time since the map was loaded (when the game loads the shrine of awakening for the first time) to the current time in-game (determined in seconds of the cycle not accounting for time in shrines) so that dragon positions could be easy-ish to determine?

**Comment by savage13** [comment]
That requires the speed of the object on the rail and knowing where the object is on the rail at a specific time.

**Comment by leoetlino** [comment]
Yeah I don't think this is feasible.
