### ISSUE TITLE
sticky lizard and fairy information is still no complete

### ISSUE THREAD

**Issue by iruzer** [zeldamods/objmap-totk#47]
Satori Mountain Foothill Cave
i see stick lizard and fairy on this place but no appear on your map.

**Comment by leoetlino** [comment]
Those are likely dynamically generated spawns (via the AutoPlacement system). Just like in BotW, some spawns are generated on the fly and the object map will not be able to show those because they are not map objects.

**Comment by hgh32** [comment]
> Those are likely dynamically generated spawns (via the AutoPlacement system). Just like in BotW, some spawns are generated on the fly and the object map will not be able to show those because they are not map objects.

Do they have a spawn area like botw?
botw's object map can view these areas
