### ISSUE TITLE
Please add a link to the usable map in the "About" box

### ISSUE THREAD

**Issue by KPJoshi** [zeldamods/objmap-totk#51]
In the BotW map repository, the "About" box at the top right has the link to the BotW object map: https://github.com/zeldamods/objmap

I was expecting to see a similar link for this repository, but I couldn't find it. I assumed that meant the map was still not publicly usable. I only recently learned that it's already available for public use. Please add a link to the repository main page as right now it's not visible anywhere!

**Comment by savage13** [comment]
Done
https://objmap-totk.zeldamods.org
Thanks
