### ISSUE TITLE
Boss/Bubbulfrog/Yiga Schematic pre-set searches?

### ISSUE THREAD

**Issue by Paperzlel** [zeldamods/objmap-totk#53]
Thinking these should be one of the options you can easily search for on the drop down menus because I'm looking for them often and it's be a neat feature to have. I was mainly thinking about:
 - Sage's Wills
 - Overworld Bosses (gleeoks, frox, molduga, talus, hinox/stalnox)
 - Yiga Schematics
 - Schema Stones
 - Bubbulfrogs
These are the ones as someone trying to route hundo I would be thinking the most about and for convenience it would be nice to have a sidebar to see these options.

**Comment by savage13** [comment]
Closed by 8275adeb41aadb4f8e41aad72e6947eccd87a15b

Oh my. Schema Stones are only pouch items and don't exist on the map, but I got the Steward Constructs and Josha that give them. :)
