### ISSUE TITLE
Filter Ghost Soldiers by weapon pool

### ISSUE THREAD

**Issue by igoticecream** [zeldamods/objmap-totk#55]
Hello, is it possible to filter Npc_MinusFieldGhost_000 by the type of weapon they can hold: spears, 2H and swords?

**Comment by leoetlino** [comment]
Yes, add "spear" (spears) or "lsword" (two-handed swords) or "sword" (one-handed swords) to the search query.

Alternatively, you can search based on the internal property ("HoldingWeaponType") directly

**Comment by igoticecream** [comment]
awesome, thanks a lot!
