### ISSUE TITLE
Show distinction for pristine (non-decayed) weapons

### ISSUE THREAD

**Issue by jordanbtucker** [zeldamods/objmap-totk#59]
TotK has pristine weapons, those not affected by Ganondorf's gloom. In game these are indicated by diamond shaped icons after the weapon name.

![image](https://github.com/zeldamods/objmap-totk/assets/468153/5fd6bd2d-bc3d-4e92-af89-d4da0afdf663)

The usual decayed weapons and the pristine versions have different internal names. For example, the decayed Traveler's Sword is `Weapon_Sword_001` while the pristine version is `Weapon_Sword_106`. This app displays both versions as just "Traveler's Sword".

It would be better if this app would display whether a weapon is pristine or not, and give the user the ability to search for pristine versions.

One possibility would be to display a diamond shape after the weapon name, like Traveler's Sword♦ or Traveler's Sword✨, but that isn't as easy to search for. Another option would be Traveler's Sword (Pristine) which is easier to search for but takes up more space.

**Comment by savage13** [comment]
I looked into this before and I believe that the pristine weapons can only be found with `Npc_MinusFieldGhost`.

If I am mistaken, please let me know.

**Comment by jordanbtucker** [comment]
As far as I know, that is correct.

**Comment by jordanbtucker** [comment]
Well, except for amiibo drops, but that is irrelevant to the map.

**Comment by leoetlino** [comment]
I've opted for just adding ✨ next to the names of the undecayed weapons.  "Giv[ing] the user the ability to search for pristine versions" is harder because the user might call them "undecayed", "non-decayed" or "pristine" weapons (or something else). Searching for the undecayed weapon actor name does already work, though.
