### ISSUE TITLE
Excludes no longer work with sky/surface/depths selection

### ISSUE THREAD

**Issue by elduende05** [zeldamods/objmap-totk#74]
Searching for any query with results (e.g. `GoronGuidePost`) on the sky/surface/depths map will add an empty exclude if you click "hide" (or import an exported query). You have to manually switch to MainField etc. to do exclusions now, which effectively killed importing exclude sets.

**Comment by savage13** [comment]
This looks to be an issue with the radar-totk backend and the API endpoint
`/objids/{map_type}/{map_name}?q=query`
and not handling the MainAndMinusField properly.

**Comment by leoetlino** [comment]
should be fixed by zeldamods/radar-totk@e6f5fbd

**Comment by savage13** [comment]
```
-    WHERE map_type = ${mapTypeQuery} ${mapNameQuery}
+    WHERE ${mapTypeQuery} ${mapNameQuery}
```

**Comment by leoetlino** [comment]
oh good catch, let me fix that
