### ISSUE TITLE
What is the name for the wooden vines that stay destroyed permanently when broken?

### ISSUE THREAD

**Issue by TimmyEdmond** [zeldamods/objmap-totk#99]
![IMG_0783](https://github.com/zeldamods/objmap-totk/assets/147433877/99be855a-30a8-47ee-90df-3b25e8d0fd50)

Thank you!

**Comment by Doge229** [comment]
My best guess is 'TreeSkyLiana', but next time I'd recommend asking in either the general TotK Discord or the Datamining Discord

**Comment by TimmyEdmond** [comment]
That’s it; thank you!
